name: test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: example
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      DATABASE_URL: "postgresql://postgres:example@localhost"
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: npx prisma db push
      - run: yarn test --runInBand --logHeapUsage
      - run: yarn test --runInBand --detectLeaks query
