name: test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tests: [10, 50]
        engine: ["library", "binary"]
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: example
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      DATABASE_URL: "postgresql://postgres:example@localhost"
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: python inflate_tests.py ${{matrix.tests}}
      - run: yarn prisma db push --schema prisma/${{matrix.engine}}.prisma
      - run: node --expose-gc ./node_modules/.bin/jest --runInBand --logHeapUsage --no-cache
