name: monitor memory usage
on:
  - push
  - workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        exposeGc: [true, false]
        tests: [2, 10]
        engine: ["library", "binary"]
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: example
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      DATABASE_URL: "postgresql://postgres:example@localhost"
    steps:
      - uses: actions/checkout@v2
      - name: setup
        run: |
          yarn
          python inflate_tests.py ${{matrix.tests}}
          yarn prisma db push --schema prisma/${{matrix.engine}}.prisma

      - name: test
        if: ${{matrix.exposeGc == false}}
        run: yarn test --runInBand --logHeapUsage --no-cache

      - name: test with exposed garbage collector
        if: ${{matrix.exposeGc == true }}
        run: node --expose-gc ./node_modules/.bin/jest --runInBand --logHeapUsage --no-cache
